name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  use_shared_binary_file:
    runs-on: ubuntu-latest

    steps:
      - name: Load binary file path from environment variable
        run: |
          SHARED_BINARY_FILE="${{ env.SHARED_BINARY_FILE }}"

      - name: Display Binary File Content
        run: |
          cat "$SHARED_BINARY_FILE"
