name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  use_shared_data:
    runs-on: ubuntu-latest

    steps:
      - name: Load folder path and file content from environment variables
        run: |
          SHARED_FOLDER="${{ env.SHARED_FOLDER }}"
          SHARED_FILE_CONTENT="${{ env.SHARED_FILE_CONTENT }}"
          echo "$SHARED_FILE_CONTENT" > "$SHARED_FOLDER/shared_file.txt"

      - name: Display Shared File Content
        run: |
          cat "$SHARED_FOLDER/shared_file.txt"
