name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  use_shared_binary_file:
    runs-on: ubuntu-latest

    steps:
      - name: Load binary file path from environment variable
        run: |
          SHARED_BINARY_FILE="${{ env.SHARED_BINARY_FILE }}"
          TEST_FOLDER="${{ github.workspace }}/test_folder"
          mkdir -p "$TEST_FOLDER"
          cp "$SHARED_BINARY_FILE" "$TEST_FOLDER"

      - name: List contents of the test folder
        run: |
          ls -la "$TEST_FOLDER"