on:
  workflow_call:

jobs:
  riscv-assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Run RISC-V tests
        run: |
          # Your test commands go her
          pwd
          mkdir test-mkdir
          ls -la

      - name: Access the test-project folder from the workspace
        run: |
          # Navigate to the workspace directory where test-project is persisted
          cd ${{ runner.workspace }}
          # Now you can access the test-project folder
          ls -la