on:
  workflow_call:

jobs:
  riscv-assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Run RISC-V tests
        run: |
          # Your test commands go her
          pwd
          mkdir test-mkdir
          ls -la
