name: Workflow A

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Directory
        run: mkdir my_folder

      - name: Create Binary File
        run: echo -n -e \\x01\\x02\\x03 > my_folder/binary_file.bin

      - name: Create Zip Archive
        run: zip my_folder/binary_file.zip my_folder/binary_file.bin
