name: test-template 

on: 
  workflow_dispatch:
  push:
    branches:
      - test-include

permissions:
  id-token: write
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create folder
        run: |
          pwd
          mkdir test-project
          ls -la

  lint:
    name: Call Lint
    uses: PriyanshOps/github_actions_cicd/.github/workflows/misp-template.yml@test-include
    # uses: ./.github/workflows/misp-template.yml@test-include
  # riscv-assembly:
  #   runs-on: ubuntu-latest
  #   needs: mips-assembly  # Ensure the MIPS job runs before this one
  #   uses: PriyanshOps/github_actions_cicd/.github/workflows/misp-template.yml@test-include

# include:
#   - template: misp-template.yml
        #   uses: PriyanshOps/github_actions_cicd/.github/actions/setup-composite/action.yaml@main
