name: test-template 

on: 
  workflow_dispatch:
  push:
    branches:
      - test-include

permissions:
  id-token: write
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create folder
        run: |
          pwd
          mkdir test-project
          ls -la

  riscv-assembly:
    runs-on: ubuntu-latest
    needs: mips-assembly  # Ensure the MIPS job runs before this one
    steps:
      - name: Use RISC-V Assembly Action
        # uses: <your-username>/<your-action-repo>@v1  # Replace with the actual repository and version
        uses: PriyanshOps/github_actions_cicd/.github/workflows/misp-template.yml@test-include

# include:
#   - template: misp-template.yml
        #   uses: PriyanshOps/github_actions_cicd/.github/actions/setup-composite/action.yaml@main
