name: Workflow A

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create a directory
        run: mkdir my_folder

      - name: Create shared_file.txt
        run: echo "This is the content of the file" > my_folder/shared_file.txt

      - name: Store folder path and file content in environment variables
        run: |
          echo "SHARED_FOLDER=my_folder" >> $GITHUB_ENV
          echo "SHARED_FILE_CONTENT=$(cat my_folder/shared_file.txt)" >> $GITHUB_ENV
