name: Workflow A

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Directory
        run: mkdir my_folder

      - name: Create Binary File
        run: echo -n -e \\x01\\x02\\x03 > my_folder/binary_file.bin

      - name: Store File Path in an Environment Variable
        run: echo "SHARED_BINARY_FILE=${{ github.workspace }}/my_folder/binary_file.bin" >> $GITHUB_ENV
