name: test-template 

on: 
  workflow_dispatch:
  push:
    branches:
      - test-include

permissions:
  id-token: write
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create folder
        run: |
          pwd
          mkdir test-project
          ls -la

include:
  - template: misp-template.yml