name: deploy

on: 
  workflow_call:

jobs:
  build-release:
    runs-on: ubuntu-latest
    using: "composite"
    # Defining the action steps(Just one step to be simple)
    steps:
    - name: deploy stack
      uses: Swatinem/rust-cache@v2

    - name: Create folder
      run: |
        pwd
        ls -la
        mkdir test-template
        ls -la
